# Generated by Django 2.2.2 on 2019-06-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='view_cnt',
        ),
    ]
