# Generated by Django 2.2.2 on 2019-06-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_view_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
